# Generated by Django 6.0.1 on 2026-01-07 14:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Skills')),
                ('level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='the level connot be less than zero'), django.core.validators.MaxValueValidator(100, message='the level connot be more than one hundred')])),
            ],
        ),
        migrations.CreateModel(
            name='SkillIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Icon name')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='skills_icon/', verbose_name='Skill Icon')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Skill Link')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='About')),
                ('image', models.ImageField(upload_to='profile/', verbose_name='Profile Image')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(related_name='profiles', to='projects.skill')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Projects')),
                ('description', models.CharField(max_length=255, verbose_name='Descriptions')),
                ('image', models.ImageField(upload_to='project/', verbose_name='Projects Images')),
                ('links', models.URLField(max_length=255, verbose_name='Git Link')),
                ('technologies', models.CharField(max_length=255, verbose_name='Technogies')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.profile')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='projects.skillicon'),
        ),
    ]
