# Generated by Django 6.0.1 on 2026-01-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_profile_learning_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aboutFooter',
            field=models.TextField(blank=True, verbose_name='AboutFooter'),
        ),
        migrations.AddField(
            model_name='profile',
            name='aboutStart',
            field=models.TextField(blank=True, verbose_name='AboutStart'),
        ),
    ]
