# Generated by Django 6.0.1 on 2026-01-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='learning_technologies',
            field=models.TextField(blank=True, verbose_name='learning_technologies'),
        ),
    ]
