# Generated by Django 6.0 on 2025-12-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='height_field',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='width_field',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
