# Generated by Django 6.0 on 2025-12-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_height_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Images'),
        ),
    ]
